### ISSUE TITLE
How to run coverage for multiple packages in a mono_repo

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/coverage#481]
Sometimes I want to gather coverage for multiple packages in a mono_repo.

I tried to be smart, and run things in parallel, but that doesn't work:

```
$ (cd ../native_assets_cli/ && dart pub global run coverage:test_with_coverage) & (cd ../native_assets_builder/ && dart pub global run coverage:test_with_coverage) & (cd ../native_toolchain_c/ && dart pub global run coverage:test_with_coverage) && wait
[1] 88093
[2] 88094
The Dart VM service is listening on http://127.0.0.1:8181/
Could not start the VM service: localhost:8181 is already in use.
Could not start the VM service: localhost:8181 is already in use.
```

Maybe there is a better way to gather coverage for multiple packages.

**Comment by phcs971** [comment]
We are using melos to manage our mono repo,

We created two scripts to handle test coverages:
```yaml
  test:coverage:
    name: Test and Check Coverage
    description: "Run test in packages with test directory and generate coverage"
    run: flutter test --coverage
    exec:
      concurrency: 5
      failFast: true
    packageFilters:
      dirExists: test

  test:coverage:all:
    name: Test All and Check Coverage
    description: "Run test in all packages with test directory and generate coverage"
    run: melos run test:coverage --no-select
```

We send results via github actions
```yaml
name: Test
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📚 Checkout
        uses: actions/checkout@v3

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2

      - name: ⚙️ Setup Melos
        uses: bluefireteam/melos-action@v2

      - name: 🧪 Test
        run: melos run test:coverage:all

      - name: 📊 Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ...
          fail_ci_if_error: true
```
