### ISSUE TITLE
Example repo and coverage.json

### ISSUE THREAD

**Issue by stevepeak** [dart-lang/coverage#51]
> I'm looking to add support for Dart to [codecov.io](https://codecov.io) (full disclosure: I'm the founder)

I'm not familiar with Dart and hoping someone can help show me an example `coverage.json` output file so that I can upload it to Codecov. If you have a very lean example repo I can show customers that would be great!

Thanks ~ Steve

**Comment by cbracken** [comment]
Hi Steve, thanks for checking in. Can you use LCOV format? `coverage.json` is really just an intermediate format that we use, but `format_coverage.dart` includes an LCOV formatter.

Also, the minute I get some time to work on it, I intend to add an updated coverage collection tool that spawns another VM process running the test code, collects coverage from it and emits in the requested format in one go rather than via the current two step process. That might simplify things a bit for you.

**Comment by stevepeak** [comment]
Thank you for the update! Producing an `lcov` file would work. Please correct me if I'm wrong: that lcov does not support branch coverage which is preferable.

If a customer can simply create the lcov file then my uploader will find it. They would only have to call `codecov` [see example here](https://gist.github.com/stevepeak/761040ee6b2bedd1897d) and the file will be collected and submitted.

If it's not asking to much. I don't know Dart and it would be helpful to have an example repo like these: [Codecov Examples](https://github.com/codecov/?query=example-). If you can help me create a Dart repo I would be in heaven :)

Thank again for your help.

**Comment by cbracken** [comment]
Sounds good! I've filed #52 for example coverage code. I'll try to get to this next week.

**Comment by pulyaevskiy** [comment]
For everyone interested. I just figured out how to send lcov data generated by the `coverage` package to codecov from Travis. My very basic `.travis.yml` looks something like this:

```yaml
sudo: false

language: dart

script:
  - pub run test
  - pub global activate coverage
  - dart --observe=8111 test/all.dart &
  - sleep 1
  - pub global run coverage:collect_coverage --port=8111 -o coverage.json --resume-isolates
  - pub global run coverage:format_coverage --package-root=packages --report-on lib --in coverage.json --out lcov.info --lcov

after_success:
  - bash <(curl -s https://codecov.io/bash)
```

The sleep is kind of awkward, but it does the job.
Ideally it would be nice if the coverage package can provide additional executable which would encapsulate observatory stuff and just output the `lcov.info` as a result. Can be tricky with dartium though.
